<?php

namespace Sprint\Migration;

class Version20210521163156 extends Version {

	protected $description = "Добавлен ИБ \"Поединки\"";
	protected $moduleVersion = "3.22.2";

	/**
	 * @throws Exceptions\HelperException
	 * @return bool|void
	 */
	public function up()
	{
		$helper = $this->getHelperManager();
		$iblockId = $helper->Iblock()->saveIblock(array(
				'IBLOCK_TYPE_ID'	 => 'content',
				'LID'				 =>
				array(
						0 => 's1',
				),
				'CODE'				 => 'duels',
				'API_CODE'			 => 'Duels',
				'NAME'				 => 'Поединки',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '500',
				'LIST_PAGE_URL'		 => '',
				'DETAIL_PAGE_URL'	 => '',
				'SECTION_PAGE_URL'	 => '',
				'CANONICAL_PAGE_URL' => '',
				'PICTURE'			 => NULL,
				'DESCRIPTION'		 => '',
				'DESCRIPTION_TYPE'	 => 'text',
				'RSS_TTL'			 => '24',
				'RSS_ACTIVE'		 => 'Y',
				'RSS_FILE_ACTIVE'	 => 'N',
				'RSS_FILE_LIMIT'	 => NULL,
				'RSS_FILE_DAYS'		 => NULL,
				'RSS_YANDEX_ACTIVE'	 => 'N',
				'XML_ID'			 => NULL,
				'INDEX_ELEMENT'		 => 'N',
				'INDEX_SECTION'		 => 'N',
				'WORKFLOW'			 => 'N',
				'BIZPROC'			 => 'N',
				'SECTION_CHOOSER'	 => 'L',
				'LIST_MODE'			 => 'C',
				'RIGHTS_MODE'		 => 'S',
				'SECTION_PROPERTY'	 => 'Y',
				'PROPERTY_INDEX'	 => 'N',
				'VERSION'			 => '1',
				'LAST_CONV_ELEMENT'	 => '0',
				'SOCNET_GROUP_ID'	 => NULL,
				'EDIT_FILE_BEFORE'	 => '',
				'EDIT_FILE_AFTER'	 => '',
				'SECTIONS_NAME'		 => 'Разделы',
				'SECTION_NAME'		 => 'Раздел',
				'ELEMENTS_NAME'		 => 'Поединки',
				'ELEMENT_NAME'		 => 'Поединок',
				'EXTERNAL_ID'		 => NULL,
				'LANG_DIR'			 => '/',
				'ELEMENT_ADD'		 => 'Добавить поединок',
				'ELEMENT_EDIT'		 => 'Изменить поединок',
				'ELEMENT_DELETE'	 => 'Удалить поединок',
				'SECTION_ADD'		 => 'Добавить раздел',
				'SECTION_EDIT'		 => 'Изменить раздел',
				'SECTION_DELETE'	 => 'Удалить раздел',
		));
		$helper->Iblock()->saveIblockFields($iblockId,
			array(
				'IBLOCK_SECTION'			 =>
				array(
						'NAME'			 => 'Привязка к разделам',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 =>
						array(
								'KEEP_IBLOCK_SECTION_ID' => 'N',
						),
				),
				'ACTIVE'					 =>
				array(
						'NAME'			 => 'Активность',
						'IS_REQUIRED'	 => 'Y',
						'DEFAULT_VALUE'	 => 'Y',
				),
				'ACTIVE_FROM'				 =>
				array(
						'NAME'			 => 'Начало активности',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 => '',
				),
				'ACTIVE_TO'					 =>
				array(
						'NAME'			 => 'Окончание активности',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 => '',
				),
				'SORT'						 =>
				array(
						'NAME'			 => 'Сортировка',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 => '0',
				),
				'NAME'						 =>
				array(
						'NAME'			 => 'Название',
						'IS_REQUIRED'	 => 'Y',
						'DEFAULT_VALUE'	 => '',
				),
				'PREVIEW_PICTURE'			 =>
				array(
						'NAME'			 => 'Картинка для анонса',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 =>
						array(
								'FROM_DETAIL'				 => 'N',
								'SCALE'						 => 'N',
								'WIDTH'						 => '',
								'HEIGHT'					 => '',
								'IGNORE_ERRORS'				 => 'N',
								'METHOD'					 => 'resample',
								'COMPRESSION'				 => 95,
								'DELETE_WITH_DETAIL'		 => 'N',
								'UPDATE_WITH_DETAIL'		 => 'N',
								'USE_WATERMARK_TEXT'		 => 'N',
								'WATERMARK_TEXT'			 => '',
								'WATERMARK_TEXT_FONT'		 => '',
								'WATERMARK_TEXT_COLOR'		 => '',
								'WATERMARK_TEXT_SIZE'		 => '',
								'WATERMARK_TEXT_POSITION'	 => 'tl',
								'USE_WATERMARK_FILE'		 => 'N',
								'WATERMARK_FILE'			 => '',
								'WATERMARK_FILE_ALPHA'		 => '',
								'WATERMARK_FILE_POSITION'	 => 'tl',
								'WATERMARK_FILE_ORDER'		 => NULL,
						),
				),
				'PREVIEW_TEXT_TYPE'			 =>
				array(
						'NAME'			 => 'Тип описания для анонса',
						'IS_REQUIRED'	 => 'Y',
						'DEFAULT_VALUE'	 => 'text',
				),
				'PREVIEW_TEXT'				 =>
				array(
						'NAME'			 => 'Описание для анонса',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 => '',
				),
				'DETAIL_PICTURE'			 =>
				array(
						'NAME'			 => 'Детальная картинка',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 =>
						array(
								'SCALE'						 => 'N',
								'WIDTH'						 => '',
								'HEIGHT'					 => '',
								'IGNORE_ERRORS'				 => 'N',
								'METHOD'					 => 'resample',
								'COMPRESSION'				 => 95,
								'USE_WATERMARK_TEXT'		 => 'N',
								'WATERMARK_TEXT'			 => '',
								'WATERMARK_TEXT_FONT'		 => '',
								'WATERMARK_TEXT_COLOR'		 => '',
								'WATERMARK_TEXT_SIZE'		 => '',
								'WATERMARK_TEXT_POSITION'	 => 'tl',
								'USE_WATERMARK_FILE'		 => 'N',
								'WATERMARK_FILE'			 => '',
								'WATERMARK_FILE_ALPHA'		 => '',
								'WATERMARK_FILE_POSITION'	 => 'tl',
								'WATERMARK_FILE_ORDER'		 => NULL,
						),
				),
				'DETAIL_TEXT_TYPE'			 =>
				array(
						'NAME'			 => 'Тип детального описания',
						'IS_REQUIRED'	 => 'Y',
						'DEFAULT_VALUE'	 => 'text',
				),
				'DETAIL_TEXT'				 =>
				array(
						'NAME'			 => 'Детальное описание',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 => '',
				),
				'XML_ID'					 =>
				array(
						'NAME'			 => 'Внешний код',
						'IS_REQUIRED'	 => 'Y',
						'DEFAULT_VALUE'	 => '',
				),
				'CODE'						 =>
				array(
						'NAME'			 => 'Символьный код',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 =>
						array(
								'UNIQUE'			 => 'N',
								'TRANSLITERATION'	 => 'N',
								'TRANS_LEN'			 => 100,
								'TRANS_CASE'		 => 'L',
								'TRANS_SPACE'		 => '-',
								'TRANS_OTHER'		 => '-',
								'TRANS_EAT'			 => 'Y',
								'USE_GOOGLE'		 => 'N',
						),
				),
				'TAGS'						 =>
				array(
						'NAME'			 => 'Теги',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 => '',
				),
				'SECTION_NAME'				 =>
				array(
						'NAME'			 => 'Название',
						'IS_REQUIRED'	 => 'Y',
						'DEFAULT_VALUE'	 => '',
				),
				'SECTION_PICTURE'			 =>
				array(
						'NAME'			 => 'Картинка для анонса',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 =>
						array(
								'FROM_DETAIL'				 => 'N',
								'SCALE'						 => 'N',
								'WIDTH'						 => '',
								'HEIGHT'					 => '',
								'IGNORE_ERRORS'				 => 'N',
								'METHOD'					 => 'resample',
								'COMPRESSION'				 => 95,
								'DELETE_WITH_DETAIL'		 => 'N',
								'UPDATE_WITH_DETAIL'		 => 'N',
								'USE_WATERMARK_TEXT'		 => 'N',
								'WATERMARK_TEXT'			 => '',
								'WATERMARK_TEXT_FONT'		 => '',
								'WATERMARK_TEXT_COLOR'		 => '',
								'WATERMARK_TEXT_SIZE'		 => '',
								'WATERMARK_TEXT_POSITION'	 => 'tl',
								'USE_WATERMARK_FILE'		 => 'N',
								'WATERMARK_FILE'			 => '',
								'WATERMARK_FILE_ALPHA'		 => '',
								'WATERMARK_FILE_POSITION'	 => 'tl',
								'WATERMARK_FILE_ORDER'		 => NULL,
						),
				),
				'SECTION_DESCRIPTION_TYPE'	 =>
				array(
						'NAME'			 => 'Тип описания',
						'IS_REQUIRED'	 => 'Y',
						'DEFAULT_VALUE'	 => 'text',
				),
				'SECTION_DESCRIPTION'		 =>
				array(
						'NAME'			 => 'Описание',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 => '',
				),
				'SECTION_DETAIL_PICTURE'	 =>
				array(
						'NAME'			 => 'Детальная картинка',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 =>
						array(
								'SCALE'						 => 'N',
								'WIDTH'						 => '',
								'HEIGHT'					 => '',
								'IGNORE_ERRORS'				 => 'N',
								'METHOD'					 => 'resample',
								'COMPRESSION'				 => 95,
								'USE_WATERMARK_TEXT'		 => 'N',
								'WATERMARK_TEXT'			 => '',
								'WATERMARK_TEXT_FONT'		 => '',
								'WATERMARK_TEXT_COLOR'		 => '',
								'WATERMARK_TEXT_SIZE'		 => '',
								'WATERMARK_TEXT_POSITION'	 => 'tl',
								'USE_WATERMARK_FILE'		 => 'N',
								'WATERMARK_FILE'			 => '',
								'WATERMARK_FILE_ALPHA'		 => '',
								'WATERMARK_FILE_POSITION'	 => 'tl',
								'WATERMARK_FILE_ORDER'		 => NULL,
						),
				),
				'SECTION_XML_ID'			 =>
				array(
						'NAME'			 => 'Внешний код',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 => '',
				),
				'SECTION_CODE'				 =>
				array(
						'NAME'			 => 'Символьный код',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 =>
						array(
								'UNIQUE'			 => 'N',
								'TRANSLITERATION'	 => 'N',
								'TRANS_LEN'			 => 100,
								'TRANS_CASE'		 => 'L',
								'TRANS_SPACE'		 => '-',
								'TRANS_OTHER'		 => '-',
								'TRANS_EAT'			 => 'Y',
								'USE_GOOGLE'		 => 'N',
						),
				),
		));
		$helper->Iblock()->saveGroupPermissions($iblockId, array(
				'administrators' => 'X',
				'everyone'		 => 'R',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Турнир',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '100',
				'CODE'				 => 'TOURNAMENT',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'E',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => 'content:tournament',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'EAutocomplete',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW'			 => 'E',
						'SHOW_ADD'		 => 'N',
						'MAX_WIDTH'		 => 0,
						'MIN_HEIGHT'	 => 24,
						'MAX_HEIGHT'	 => 1000,
						'BAN_SYM'		 => ',;',
						'REP_SYM'		 => ' ',
						'OTHER_REP_SYM'	 => '',
						'IBLOCK_MESS'	 => 'N',
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Весовая категория',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '110',
				'CODE'				 => 'WEIGHT_CATEGORY',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'E',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => 'dictionaries:weight_category',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'EAutocomplete',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW'			 => 'E',
						'SHOW_ADD'		 => 'Y',
						'MAX_WIDTH'		 => 0,
						'MIN_HEIGHT'	 => 24,
						'MAX_HEIGHT'	 => 1000,
						'BAN_SYM'		 => ',;',
						'REP_SYM'		 => ' ',
						'OTHER_REP_SYM'	 => '',
						'IBLOCK_MESS'	 => 'N',
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Количество раундов',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '120',
				'CODE'				 => 'ROUNDS',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Место проведения',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '130',
				'CODE'				 => 'PLACE',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'E',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => 'dictionaries:cities',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'EAutocomplete',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW'			 => 'E',
						'SHOW_ADD'		 => 'Y',
						'MAX_WIDTH'		 => 0,
						'MIN_HEIGHT'	 => 24,
						'MAX_HEIGHT'	 => 1000,
						'BAN_SYM'		 => ',;',
						'REP_SYM'		 => ' ',
						'OTHER_REP_SYM'	 => '',
						'IBLOCK_MESS'	 => 'N',
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Дата проведения',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '140',
				'CODE'				 => 'DATE',
				'DEFAULT_VALUE'		 => NULL,
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'DateTime',
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Участники',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '150',
				'CODE'				 => 'FIGHTERS',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'E',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'Y',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => 'content:fighters',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'EAutocomplete',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW'			 => 'E',
						'SHOW_ADD'		 => 'N',
						'MAX_WIDTH'		 => 0,
						'MIN_HEIGHT'	 => 24,
						'MAX_HEIGHT'	 => 1000,
						'BAN_SYM'		 => ',;',
						'REP_SYM'		 => ' ',
						'OTHER_REP_SYM'	 => '',
						'IBLOCK_MESS'	 => 'N',
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Победитель',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '160',
				'CODE'				 => 'WINNER',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'E',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => 'content:fighters',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'EAutocomplete',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW'			 => 'E',
						'SHOW_ADD'		 => 'N',
						'MAX_WIDTH'		 => 0,
						'MIN_HEIGHT'	 => 24,
						'MAX_HEIGHT'	 => 1000,
						'BAN_SYM'		 => ',;',
						'REP_SYM'		 => ' ',
						'OTHER_REP_SYM'	 => '',
						'IBLOCK_MESS'	 => 'N',
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Результат (время)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '170',
				'CODE'				 => 'RESULT_TIME',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Результат (раунд)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '180',
				'CODE'				 => 'RESULT_ROUND',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'N',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '10',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Результат (метод)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '190',
				'CODE'				 => 'RESULT_METHOD',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'E',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => 'dictionaries:duel_result',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'EAutocomplete',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW'			 => 'E',
						'SHOW_ADD'		 => 'N',
						'MAX_WIDTH'		 => 0,
						'MIN_HEIGHT'	 => 24,
						'MAX_HEIGHT'	 => 1000,
						'BAN_SYM'		 => ',;',
						'REP_SYM'		 => ' ',
						'OTHER_REP_SYM'	 => '',
						'IBLOCK_MESS'	 => 'N',
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Ничья',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '200',
				'CODE'				 => 'IS_DRAW',
				'DEFAULT_VALUE'		 => 0,
				'PROPERTY_TYPE'		 => 'N',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'SASDCheckboxNum',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW' =>
						array(
								0	 => 'Нет',
								1	 => 'Да',
						),
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Поединок завершен',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '210',
				'CODE'				 => 'IS_COMPLETE',
				'DEFAULT_VALUE'		 => 0,
				'PROPERTY_TYPE'		 => 'N',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'SASDCheckboxNum',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW' =>
						array(
								0	 => 'Нет',
								1	 => 'Да',
						),
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Прелим',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '220',
				'CODE'				 => 'IS_PRELIM',
				'DEFAULT_VALUE'		 => 0,
				'PROPERTY_TYPE'		 => 'N',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'SASDCheckboxNum',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW' =>
						array(
								0	 => 'Нет',
								1	 => 'Да',
						),
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Гранд-при',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '230',
				'CODE'				 => 'IS_GRAND_PRIX',
				'DEFAULT_VALUE'		 => 0,
				'PROPERTY_TYPE'		 => 'N',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'SASDCheckboxNum',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW' =>
						array(
								0	 => 'Нет',
								1	 => 'Да',
						),
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Гранд-при заголовок бойца слева (ru)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '300',
				'CODE'				 => 'GRAND_PRIX_LEFT_NAME_RU',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Гранд-при заголовок бойца справа (ru)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '310',
				'CODE'				 => 'GRAND_PRIX_RIGHT_NAME_RU',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Гранд-при этап (ru)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '320',
				'CODE'				 => 'GRAND_PRIX_STAGE_RU',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Гранд-при заголовок бойца слева (en)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '500',
				'CODE'				 => 'GRAND_PRIX_LEFT_NAME_EN',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Гранд-при заголовок бойца справа (en)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '500',
				'CODE'				 => 'GRAND_PRIX_RIGHT_NAME_EN',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Гранд-при этап (en)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '500',
				'CODE'				 => 'GRAND_PRIX_STAGE_EN',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->UserOptions()->saveElementForm($iblockId,
			array(
				'Поединок|edit1' =>
				array(
						'NAME'						 => 'Название (любое)',
						'PROPERTY_TOURNAMENT'		 => 'Турнир',
						'PROPERTY_WEIGHT_CATEGORY'	 => 'Весовая категория',
						'PROPERTY_ROUNDS'			 => 'Количество раундов',
						'PROPERTY_PLACE'			 => 'Место проведения',
						'PROPERTY_DATE'				 => 'Дата проведения',
						'PROPERTY_FIGHTERS'			 => 'Участники',
						'PROPERTY_WINNER'			 => 'Победитель',
						'PROPERTY_RESULT_TIME'		 => 'Результат (время)',
						'PROPERTY_RESULT_ROUND'		 => 'Результат (раунд)',
						'PROPERTY_RESULT_METHOD'	 => 'Результат (метод)',
						'PROPERTY_IS_DRAW'			 => 'Ничья',
						'PROPERTY_IS_COMPLETE'		 => 'Поединок завершен',
						'PROPERTY_IS_PRELIM'		 => 'Прелим',
						'edit1_csection1'			 => 'Гранд-при',
						'PROPERTY_IS_GRAND_PRIX'	 => 'Гранд-при',
				),
				'Ru|cedit2'		 =>
				array(
						'PROPERTY_GRAND_PRIX_LEFT_NAME_RU'	 => 'Гранд-при заголовок бойца слева',
						'PROPERTY_GRAND_PRIX_RIGHT_NAME_RU'	 => 'Гранд-при заголовок бойца справа',
						'PROPERTY_GRAND_PRIX_STAGE_RU'		 => 'Гранд-при этап',
				),
				'En|cedit3'		 =>
				array(
						'PROPERTY_GRAND_PRIX_LEFT_NAME_EN'	 => 'Гранд-при заголовок бойца слева',
						'PROPERTY_GRAND_PRIX_RIGHT_NAME_EN'	 => 'Гранд-при заголовок бойца справа',
						'PROPERTY_GRAND_PRIX_STAGE_EN'		 => 'Гранд-при этап',
				),
		));
		$helper->UserOptions()->saveElementGrid($iblockId,
			array(
				'views'			 =>
				array(
						'default' =>
						array(
								'columns'			 =>
								array(
										0	 => 'NAME',
										1	 => 'ACTIVE',
										2	 => 'SORT',
										3	 => 'EXTERNAL_ID',
								),
								'columns_sizes'		 =>
								array(
										'expand'	 => 1,
										'columns'	 =>
										array(
										),
								),
								'sticked_columns'	 =>
								array(
								),
								'last_sort_by'		 => 'id',
								'last_sort_order'	 => 'asc',
								'custom_names'		 => NULL,
						),
				),
				'filters'		 =>
				array(
				),
				'current_view'	 => 'default',
		));
	}

	public function down()
	{
		//your code ...
	}

}
