<?php

namespace Sprint\Migration;

class Version20210521163039 extends Version {

	protected $description = "Добавлен ИБ \"Турниры\"";
	protected $moduleVersion = "3.22.2";

	/**
	 * @throws Exceptions\HelperException
	 * @return bool|void
	 */
	public function up()
	{
		$helper = $this->getHelperManager();
		$helper->Iblock()->saveIblockType(array(
				'ID'				 => 'content',
				'SECTIONS'			 => 'Y',
				'EDIT_FILE_BEFORE'	 => '',
				'EDIT_FILE_AFTER'	 => '',
				'IN_RSS'			 => 'N',
				'SORT'				 => '100',
				'LANG'				 =>
				array(
						'ru' =>
						array(
								'NAME'			 => 'Контент (общий)',
								'SECTION_NAME'	 => '',
								'ELEMENT_NAME'	 => '',
						),
						'en' =>
						array(
								'NAME'			 => 'Контент (общий)',
								'SECTION_NAME'	 => '',
								'ELEMENT_NAME'	 => '',
						),
				),
		));
		$iblockId = $helper->Iblock()->saveIblock(array(
				'IBLOCK_TYPE_ID'	 => 'content',
				'LID'				 =>
				array(
						0 => 's1',
				),
				'CODE'				 => 'tournament',
				'API_CODE'			 => 'Tournament',
				'NAME'				 => 'Турниры',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '500',
				'LIST_PAGE_URL'		 => '#SITE_DIR#/tournaments/',
				'DETAIL_PAGE_URL'	 => '#SITE_DIR#/tournaments/#ELEMENT_CODE#/',
				'SECTION_PAGE_URL'	 => '',
				'CANONICAL_PAGE_URL' => '',
				'PICTURE'			 => NULL,
				'DESCRIPTION'		 => '',
				'DESCRIPTION_TYPE'	 => 'text',
				'RSS_TTL'			 => '24',
				'RSS_ACTIVE'		 => 'Y',
				'RSS_FILE_ACTIVE'	 => 'N',
				'RSS_FILE_LIMIT'	 => NULL,
				'RSS_FILE_DAYS'		 => NULL,
				'RSS_YANDEX_ACTIVE'	 => 'N',
				'XML_ID'			 => NULL,
				'INDEX_ELEMENT'		 => 'Y',
				'INDEX_SECTION'		 => 'N',
				'WORKFLOW'			 => 'N',
				'BIZPROC'			 => 'N',
				'SECTION_CHOOSER'	 => 'L',
				'LIST_MODE'			 => 'C',
				'RIGHTS_MODE'		 => 'S',
				'SECTION_PROPERTY'	 => 'Y',
				'PROPERTY_INDEX'	 => 'N',
				'VERSION'			 => '1',
				'LAST_CONV_ELEMENT'	 => '0',
				'SOCNET_GROUP_ID'	 => NULL,
				'EDIT_FILE_BEFORE'	 => '',
				'EDIT_FILE_AFTER'	 => '',
				'SECTIONS_NAME'		 => 'Разделы',
				'SECTION_NAME'		 => 'Раздел',
				'ELEMENTS_NAME'		 => 'Турниры',
				'ELEMENT_NAME'		 => 'Турнир',
				'EXTERNAL_ID'		 => NULL,
				'LANG_DIR'			 => '/',
				'ELEMENT_ADD'		 => 'Добавить турнир',
				'ELEMENT_EDIT'		 => 'Изменить турнир',
				'ELEMENT_DELETE'	 => 'Удалить турнир',
				'SECTION_ADD'		 => 'Добавить раздел',
				'SECTION_EDIT'		 => 'Изменить раздел',
				'SECTION_DELETE'	 => 'Удалить раздел',
		));
		$helper->Iblock()->saveIblockFields($iblockId,
			array(
				'IBLOCK_SECTION'			 =>
				array(
						'NAME'			 => 'Привязка к разделам',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 =>
						array(
								'KEEP_IBLOCK_SECTION_ID' => 'N',
						),
				),
				'ACTIVE'					 =>
				array(
						'NAME'			 => 'Активность',
						'IS_REQUIRED'	 => 'Y',
						'DEFAULT_VALUE'	 => 'Y',
				),
				'ACTIVE_FROM'				 =>
				array(
						'NAME'			 => 'Начало активности',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 => '',
				),
				'ACTIVE_TO'					 =>
				array(
						'NAME'			 => 'Окончание активности',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 => '',
				),
				'SORT'						 =>
				array(
						'NAME'			 => 'Сортировка',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 => '0',
				),
				'NAME'						 =>
				array(
						'NAME'			 => 'Название',
						'IS_REQUIRED'	 => 'Y',
						'DEFAULT_VALUE'	 => '',
				),
				'PREVIEW_PICTURE'			 =>
				array(
						'NAME'			 => 'Картинка для анонса',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 =>
						array(
								'FROM_DETAIL'				 => 'N',
								'SCALE'						 => 'N',
								'WIDTH'						 => '',
								'HEIGHT'					 => '',
								'IGNORE_ERRORS'				 => 'N',
								'METHOD'					 => 'resample',
								'COMPRESSION'				 => 95,
								'DELETE_WITH_DETAIL'		 => 'N',
								'UPDATE_WITH_DETAIL'		 => 'N',
								'USE_WATERMARK_TEXT'		 => 'N',
								'WATERMARK_TEXT'			 => '',
								'WATERMARK_TEXT_FONT'		 => '',
								'WATERMARK_TEXT_COLOR'		 => '',
								'WATERMARK_TEXT_SIZE'		 => '',
								'WATERMARK_TEXT_POSITION'	 => 'tl',
								'USE_WATERMARK_FILE'		 => 'N',
								'WATERMARK_FILE'			 => '',
								'WATERMARK_FILE_ALPHA'		 => '',
								'WATERMARK_FILE_POSITION'	 => 'tl',
								'WATERMARK_FILE_ORDER'		 => NULL,
						),
				),
				'PREVIEW_TEXT_TYPE'			 =>
				array(
						'NAME'			 => 'Тип описания для анонса',
						'IS_REQUIRED'	 => 'Y',
						'DEFAULT_VALUE'	 => 'text',
				),
				'PREVIEW_TEXT'				 =>
				array(
						'NAME'			 => 'Описание для анонса',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 => '',
				),
				'DETAIL_PICTURE'			 =>
				array(
						'NAME'			 => 'Детальная картинка',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 =>
						array(
								'SCALE'						 => 'N',
								'WIDTH'						 => '',
								'HEIGHT'					 => '',
								'IGNORE_ERRORS'				 => 'N',
								'METHOD'					 => 'resample',
								'COMPRESSION'				 => 95,
								'USE_WATERMARK_TEXT'		 => 'N',
								'WATERMARK_TEXT'			 => '',
								'WATERMARK_TEXT_FONT'		 => '',
								'WATERMARK_TEXT_COLOR'		 => '',
								'WATERMARK_TEXT_SIZE'		 => '',
								'WATERMARK_TEXT_POSITION'	 => 'tl',
								'USE_WATERMARK_FILE'		 => 'N',
								'WATERMARK_FILE'			 => '',
								'WATERMARK_FILE_ALPHA'		 => '',
								'WATERMARK_FILE_POSITION'	 => 'tl',
								'WATERMARK_FILE_ORDER'		 => NULL,
						),
				),
				'DETAIL_TEXT_TYPE'			 =>
				array(
						'NAME'			 => 'Тип детального описания',
						'IS_REQUIRED'	 => 'Y',
						'DEFAULT_VALUE'	 => 'text',
				),
				'DETAIL_TEXT'				 =>
				array(
						'NAME'			 => 'Детальное описание',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 => '',
				),
				'XML_ID'					 =>
				array(
						'NAME'			 => 'Внешний код',
						'IS_REQUIRED'	 => 'Y',
						'DEFAULT_VALUE'	 => '',
				),
				'CODE'						 =>
				array(
						'NAME'			 => 'Символьный код',
						'IS_REQUIRED'	 => 'Y',
						'DEFAULT_VALUE'	 =>
						array(
								'UNIQUE'			 => 'Y',
								'TRANSLITERATION'	 => 'N',
								'TRANS_LEN'			 => 100,
								'TRANS_CASE'		 => 'L',
								'TRANS_SPACE'		 => '-',
								'TRANS_OTHER'		 => '-',
								'TRANS_EAT'			 => 'Y',
								'USE_GOOGLE'		 => 'N',
						),
				),
				'TAGS'						 =>
				array(
						'NAME'			 => 'Теги',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 => '',
				),
				'SECTION_NAME'				 =>
				array(
						'NAME'			 => 'Название',
						'IS_REQUIRED'	 => 'Y',
						'DEFAULT_VALUE'	 => '',
				),
				'SECTION_PICTURE'			 =>
				array(
						'NAME'			 => 'Картинка для анонса',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 =>
						array(
								'FROM_DETAIL'				 => 'N',
								'SCALE'						 => 'N',
								'WIDTH'						 => '',
								'HEIGHT'					 => '',
								'IGNORE_ERRORS'				 => 'N',
								'METHOD'					 => 'resample',
								'COMPRESSION'				 => 95,
								'DELETE_WITH_DETAIL'		 => 'N',
								'UPDATE_WITH_DETAIL'		 => 'N',
								'USE_WATERMARK_TEXT'		 => 'N',
								'WATERMARK_TEXT'			 => '',
								'WATERMARK_TEXT_FONT'		 => '',
								'WATERMARK_TEXT_COLOR'		 => '',
								'WATERMARK_TEXT_SIZE'		 => '',
								'WATERMARK_TEXT_POSITION'	 => 'tl',
								'USE_WATERMARK_FILE'		 => 'N',
								'WATERMARK_FILE'			 => '',
								'WATERMARK_FILE_ALPHA'		 => '',
								'WATERMARK_FILE_POSITION'	 => 'tl',
								'WATERMARK_FILE_ORDER'		 => NULL,
						),
				),
				'SECTION_DESCRIPTION_TYPE'	 =>
				array(
						'NAME'			 => 'Тип описания',
						'IS_REQUIRED'	 => 'Y',
						'DEFAULT_VALUE'	 => 'text',
				),
				'SECTION_DESCRIPTION'		 =>
				array(
						'NAME'			 => 'Описание',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 => '',
				),
				'SECTION_DETAIL_PICTURE'	 =>
				array(
						'NAME'			 => 'Детальная картинка',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 =>
						array(
								'SCALE'						 => 'N',
								'WIDTH'						 => '',
								'HEIGHT'					 => '',
								'IGNORE_ERRORS'				 => 'N',
								'METHOD'					 => 'resample',
								'COMPRESSION'				 => 95,
								'USE_WATERMARK_TEXT'		 => 'N',
								'WATERMARK_TEXT'			 => '',
								'WATERMARK_TEXT_FONT'		 => '',
								'WATERMARK_TEXT_COLOR'		 => '',
								'WATERMARK_TEXT_SIZE'		 => '',
								'WATERMARK_TEXT_POSITION'	 => 'tl',
								'USE_WATERMARK_FILE'		 => 'N',
								'WATERMARK_FILE'			 => '',
								'WATERMARK_FILE_ALPHA'		 => '',
								'WATERMARK_FILE_POSITION'	 => 'tl',
								'WATERMARK_FILE_ORDER'		 => NULL,
						),
				),
				'SECTION_XML_ID'			 =>
				array(
						'NAME'			 => 'Внешний код',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 => '',
				),
				'SECTION_CODE'				 =>
				array(
						'NAME'			 => 'Символьный код',
						'IS_REQUIRED'	 => 'N',
						'DEFAULT_VALUE'	 =>
						array(
								'UNIQUE'			 => 'N',
								'TRANSLITERATION'	 => 'N',
								'TRANS_LEN'			 => 100,
								'TRANS_CASE'		 => 'L',
								'TRANS_SPACE'		 => '-',
								'TRANS_OTHER'		 => '-',
								'TRANS_EAT'			 => 'Y',
								'USE_GOOGLE'		 => 'N',
						),
				),
		));
		$helper->Iblock()->saveGroupPermissions($iblockId, array(
				'administrators' => 'X',
				'everyone'		 => 'R',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Серия турниров',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '100',
				'CODE'				 => 'SERIES',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'E',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => 'dictionaries:tournament_series',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'EAutocomplete',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW'			 => 'E',
						'SHOW_ADD'		 => 'Y',
						'MAX_WIDTH'		 => 0,
						'MIN_HEIGHT'	 => 24,
						'MAX_HEIGHT'	 => 1000,
						'BAN_SYM'		 => ',;',
						'REP_SYM'		 => ' ',
						'OTHER_REP_SYM'	 => '',
						'IBLOCK_MESS'	 => 'N',
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Место проведения',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '120',
				'CODE'				 => 'PLACE',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'E',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => 'dictionaries:cities',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'EAutocomplete',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW'			 => 'E',
						'SHOW_ADD'		 => 'N',
						'MAX_WIDTH'		 => 0,
						'MIN_HEIGHT'	 => 24,
						'MAX_HEIGHT'	 => 1000,
						'BAN_SYM'		 => ',;',
						'REP_SYM'		 => ' ',
						'OTHER_REP_SYM'	 => '',
						'IBLOCK_MESS'	 => 'N',
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Ссылка на стрим',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '130',
				'CODE'				 => 'STREAM',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '60',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Отображать стрим на главной странице',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '140',
				'CODE'				 => 'SHOW_ON_MAIN_PAGE',
				'DEFAULT_VALUE'		 => 0,
				'PROPERTY_TYPE'		 => 'N',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'SASDCheckboxNum',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW' =>
						array(
								0	 => 'Нет',
								1	 => 'Да',
						),
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Ссылка для покупку билетов',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '150',
				'CODE'				 => 'BUY_TICKET_URL',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '60',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Ссылка для покупку стрима',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '160',
				'CODE'				 => 'BUY_STREAM_URL',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '60',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Отображать тексты на внутренней карточке турнира',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '170',
				'CODE'				 => 'SHOW_TEXTS_ON_CARD',
				'DEFAULT_VALUE'		 => 0,
				'PROPERTY_TYPE'		 => 'N',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'SASDCheckboxNum',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW' =>
						array(
								0	 => 'Нет',
								1	 => 'Да',
						),
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Открывать ссылку покупки билета в новой вкладке',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '180',
				'CODE'				 => 'OPEN_BUY_TICKET_IN_NEW_TAB',
				'DEFAULT_VALUE'		 => 0,
				'PROPERTY_TYPE'		 => 'N',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'SASDCheckboxNum',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW' =>
						array(
								0	 => 'Нет',
								1	 => 'Да',
						),
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Открывать ссылку покупки стрима в новой вкладке',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '190',
				'CODE'				 => 'OPEN_BUY_STREAM_IN_NEW_TAB',
				'DEFAULT_VALUE'		 => 0,
				'PROPERTY_TYPE'		 => 'N',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'SASDCheckboxNum',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW' =>
						array(
								0	 => 'Нет',
								1	 => 'Да',
						),
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Отображать подраздел Гранд-при',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '200',
				'CODE'				 => 'SHOW_GRAND_PRIX',
				'DEFAULT_VALUE'		 => 0,
				'PROPERTY_TYPE'		 => 'N',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'SASDCheckboxNum',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW' =>
						array(
								0	 => 'Нет',
								1	 => 'Да',
						),
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Дата проведения',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '210',
				'CODE'				 => 'DATE',
				'DEFAULT_VALUE'		 => NULL,
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'DateTime',
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Название (ru)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '300',
				'CODE'				 => 'NAME_RU',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Изображение (desktop) (ru)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '310',
				'CODE'				 => 'IMAGE_DESKTOP_RU',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'F',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => 'jpg, gif, bmp, png, jpeg',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Изображение (mobile) (ru)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '320',
				'CODE'				 => 'IMAGE_MOBILE_RU',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'F',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => 'jpg, gif, bmp, png, jpeg',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Заголовок вкладки подраздела Гранд-при (ru)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '330',
				'CODE'				 => 'GRAND_PRIX_TITLE_RU',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Связанная новость (ru)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '340',
				'CODE'				 => 'NEWS_RU',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'E',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => 'content_ru:news_ru',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'EAutocomplete',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW'			 => 'E',
						'SHOW_ADD'		 => 'N',
						'MAX_WIDTH'		 => 0,
						'MIN_HEIGHT'	 => 24,
						'MAX_HEIGHT'	 => 1000,
						'BAN_SYM'		 => ',;',
						'REP_SYM'		 => ' ',
						'OTHER_REP_SYM'	 => '',
						'IBLOCK_MESS'	 => 'N',
				),
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Название (en)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '400',
				'CODE'				 => 'NAME_EN',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Изображение (desktop) (en)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '410',
				'CODE'				 => 'IMAGE_DESKTOP_EN',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'F',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => 'jpg, gif, bmp, png, jpeg',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Изображение (mobile) (en)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '420',
				'CODE'				 => 'IMAGE_MOBILE_EN',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'F',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => 'jpg, gif, bmp, png, jpeg',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Заголовок вкладки подраздела Гранд-при (en)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '430',
				'CODE'				 => 'GRAND_PRIX_TITLE_EN',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'S',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => '0',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => NULL,
				'USER_TYPE_SETTINGS' => NULL,
				'HINT'				 => '',
		));
		$helper->Iblock()->saveProperty($iblockId,
			array(
				'NAME'				 => 'Связанная новость (en)',
				'ACTIVE'			 => 'Y',
				'SORT'				 => '440',
				'CODE'				 => 'NEWS_EN',
				'DEFAULT_VALUE'		 => '',
				'PROPERTY_TYPE'		 => 'E',
				'ROW_COUNT'			 => '1',
				'COL_COUNT'			 => '30',
				'LIST_TYPE'			 => 'L',
				'MULTIPLE'			 => 'N',
				'XML_ID'			 => NULL,
				'FILE_TYPE'			 => '',
				'MULTIPLE_CNT'		 => '5',
				'LINK_IBLOCK_ID'	 => 'content_en:news_en',
				'WITH_DESCRIPTION'	 => 'N',
				'SEARCHABLE'		 => 'N',
				'FILTRABLE'			 => 'N',
				'IS_REQUIRED'		 => 'N',
				'VERSION'			 => '1',
				'USER_TYPE'			 => 'EAutocomplete',
				'USER_TYPE_SETTINGS' =>
				array(
						'VIEW'			 => 'E',
						'SHOW_ADD'		 => 'N',
						'MAX_WIDTH'		 => 0,
						'MIN_HEIGHT'	 => 24,
						'MAX_HEIGHT'	 => 1000,
						'BAN_SYM'		 => ',;',
						'REP_SYM'		 => ' ',
						'OTHER_REP_SYM'	 => '',
						'IBLOCK_MESS'	 => 'N',
				),
				'HINT'				 => '',
		));
		$helper->UserOptions()->saveElementForm($iblockId,
			array(
				'Турнир|edit1'						 =>
				array(
						'ACTIVE'					 => 'Активность',
						'NAME'						 => 'Название',
						'CODE'						 => 'Символьный код',
						'PROPERTY_SERIES'			 => 'Серия турниров',
						'PROPERTY_DATE'				 => 'Дата проведения',
						'PROPERTY_PLACE'			 => 'Место проведения',
						'PROPERTY_STREAM'			 => 'Ссылка на стрим',
						'PROPERTY_SHOW_ON_MAIN_PAGE' => 'Отображать стрим на главной странице',
				),
				'Настройка карточки турнира|cedit1'	 =>
				array(
						'PROPERTY_SHOW_TEXTS_ON_CARD'			 => 'Отображать тексты на внутренней карточке турнира',
						'PROPERTY_OPEN_BUY_TICKET_IN_NEW_TAB'	 => 'Открывать ссылку покупки билета в новой вкладке',
						'PROPERTY_BUY_TICKET_URL'				 => 'Ссылка для покупку билетов',
						'PROPERTY_OPEN_BUY_STREAM_IN_NEW_TAB'	 => 'Открывать ссылку покупки стрима в новой вкладке',
						'PROPERTY_BUY_STREAM_URL'				 => 'Ссылка для покупку стрима',
				),
				'Гранд-при|cedit2'					 =>
				array(
						'PROPERTY_SHOW_GRAND_PRIX' => 'Отображать подраздел Гранд-при',
				),
				'Ru|cedit3'							 =>
				array(
						'PROPERTY_NAME_RU'				 => 'Название',
						'PROPERTY_NEWS_RU'				 => 'Связанная новость',
						'PROPERTY_IMAGE_DESKTOP_RU'		 => 'Изображение (desktop)',
						'PROPERTY_IMAGE_MOBILE_RU'		 => 'Изображение (mobile)',
						'PROPERTY_GRAND_PRIX_TITLE_RU'	 => 'Заголовок вкладки подраздела Гранд-при',
				),
				'En|cedit4'							 =>
				array(
						'PROPERTY_NAME_EN'				 => 'Название',
						'PROPERTY_NEWS_EN'				 => 'Связанная новость',
						'PROPERTY_IMAGE_DESKTOP_EN'		 => 'Изображение (desktop)',
						'PROPERTY_IMAGE_MOBILE_EN'		 => 'Изображение (mobile)',
						'PROPERTY_GRAND_PRIX_TITLE_EN'	 => 'Заголовок вкладки подраздела Гранд-при',
				),
				'SEO|edit14'						 =>
				array(
						'IPROPERTY_TEMPLATES_ELEMENT_META_TITLE'				 => 'Шаблон META TITLE',
						'IPROPERTY_TEMPLATES_ELEMENT_META_KEYWORDS'				 => 'Шаблон META KEYWORDS',
						'IPROPERTY_TEMPLATES_ELEMENT_META_DESCRIPTION'			 => 'Шаблон META DESCRIPTION',
						'IPROPERTY_TEMPLATES_ELEMENT_PAGE_TITLE'				 => 'Заголовок элемента',
						'IPROPERTY_TEMPLATES_ELEMENTS_PREVIEW_PICTURE'			 => 'Настройки для картинок анонса элементов',
						'IPROPERTY_TEMPLATES_ELEMENT_PREVIEW_PICTURE_FILE_ALT'	 => 'Шаблон ALT',
						'IPROPERTY_TEMPLATES_ELEMENT_PREVIEW_PICTURE_FILE_TITLE' => 'Шаблон TITLE',
						'IPROPERTY_TEMPLATES_ELEMENT_PREVIEW_PICTURE_FILE_NAME'	 => 'Шаблон имени файла',
						'IPROPERTY_TEMPLATES_ELEMENTS_DETAIL_PICTURE'			 => 'Настройки для детальных картинок элементов',
						'IPROPERTY_TEMPLATES_ELEMENT_DETAIL_PICTURE_FILE_ALT'	 => 'Шаблон ALT',
						'IPROPERTY_TEMPLATES_ELEMENT_DETAIL_PICTURE_FILE_TITLE'	 => 'Шаблон TITLE',
						'IPROPERTY_TEMPLATES_ELEMENT_DETAIL_PICTURE_FILE_NAME'	 => 'Шаблон имени файла',
						'SEO_ADDITIONAL'										 => 'Дополнительно',
						'TAGS'													 => 'Теги',
				),
		));
		$helper->UserOptions()->saveElementGrid($iblockId,
			array(
				'views'			 =>
				array(
						'default' =>
						array(
								'columns'			 =>
								array(
										0	 => 'NAME',
										1	 => 'ACTIVE',
										2	 => 'SORT',
										3	 => 'EXTERNAL_ID',
										4	 => 'TIMESTAMP_X',
										5	 => 'ID',
										6	 => 'PROPERTY_PLACE',
								),
								'columns_sizes'		 =>
								array(
										'expand'	 => 1,
										'columns'	 =>
										array(
										),
								),
								'sticked_columns'	 =>
								array(
								),
								'custom_names'		 => NULL,
								'last_sort_by'		 => 'id',
								'last_sort_order'	 => 'asc',
								'page_size'			 => 20,
						),
				),
				'filters'		 =>
				array(
				),
				'current_view'	 => 'default',
		));
	}

	public function down()
	{
		//your code ...
	}

}
